import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import WhatsAppIcon from "@/components/whatsappIco";

const inter = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={` bg-white ${inter.className}`}>
        <WhatsAppIcon phone="+966533424925" />
        {children}
      </body>
    </html>
  );
}
